version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    environment:
      - IMAGE_NAME: jtwp470/aws-tools-with-docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull ${IMAGE_NAME}
      - run: docker build -t ${IMAGE_NAME} .
      - run:
          name: Show aws tool version
          command: |
            docker run --rm ${IMAGE_NAME} aws --version
            docker run --rm ${IMAGE_NAME} eb --version
            docker run --rm ${IMAGE_NAME} ecs-cli --version
      - run:
          name: Show docker tool version
          command: |
            docker run --rm ${IMAGE_NAME} docker --version
            docker run --rm ${IMAGE_NAME} docker-compose --version
            docker run --rm ${IMAGE_NAME} docker-machine --version
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin
              docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${CIRCLE_SHA1}
              docker push ${IMAGE_NAME}
              docker push ${IMAGE_NAME}:${CIRCLE_SHA1}
            fi

workflows:
  version: 2
  test-docker-build-and-push:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - build
