version: 2
jobs:
  test:
    docker:
      - image: jtwp470/aws-tools-with-docker
    steps:
      - run:
          name: Show aws cli version
          command: |
            aws --version
      - run:
          name: Show aws eb version
          command: |
            eb --version

  docker-build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t jtwp470/aws-tools-with-docker .
      - run: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - run: docker push jtwp470/aws-tools-with-docker

workflows:
  version: 2
  test-and-docker-build:
    jobs:
      - test
      - docker-build:
          requires:
            - test
          filters:
            branches:
              only: master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - test
      - docker-build:
          requires:
            - test
